DEVOPS-3254: fix(deployment scheduler): use apps/v1 instead of extenstion/v1beta1 for deployments
citizensadvice/kube-schedule-scaler pull request #1
Opened 2020-06-10 09:23 UTC by ruthwells

And fix rbac api version.

Tested in minikube - brings casebook web/worker up and down fine.

2020-06-10 11:33 UTC, zhelyan commented on schedule_scaling/schedule_scaling.py
> +    # need to copy cadeployment.py to override pykube.Deployment with the correct api version
why does it need to be copied over to the temp dir? The file is already in the project

2020-06-10 12:12 UTC, ruthwells commented on schedule_scaling/schedule_scaling.py
> +    # need to copy cadeployment.py to override pykube.Deployment with the correct api version
@zhelyan, yes, that's what I thought. But until I copied it across, the jobs running from the temp dir were failing: 
`Traceback (most recent call last):
  File "/tmp/scaling_jobs/casebook-worker-0.py", line 5, in <module>
    import cadeployment
ImportError: No module named 'cadeployment'
Traceback (most recent call last):
  File "/tmp/scaling_jobs/casebook-web-0.py", line 5, in <module>
    import cadeployment
ImportError: No module named 'cadeployment'
`
Copying the file across solved the problem (but maybe not in the correct way...)

2020-06-10 13:12 UTC, michelesr commented on Dockerfile
> +COPY ./cadeployment.py /root/schedule_scaling
don't call it cadeployment please... this is a public repository and the code is generic enough than can be used by other organizations

2020-06-10 13:13 UTC, michelesr commented on cadeployment.py
> +class CADeployment(pykube.Deployment):
same as above

2020-06-10 13:13 UTC, michelesr commented on schedule_scaling/schedule_scaling.py
> +import cadeployment
same as above

2020-06-10 13:13 UTC, michelesr commented on schedule_scaling/schedule_scaling.py
> +    # need to copy cadeployment.py to override pykube.Deployment with the correct api version
this can be fixed by setting the `PYTHONPATH` environment variable to contain `/root/shedule_scaling`

2020-06-10 13:16 UTC, michelesr requested changes
Please use a generic name for the custom deployment class and module (not CA), and set `PYTHONPATH` to make the module available without copying the file on the same directory.

https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH

2020-06-10 13:21 UTC, michelesr commented on cadeployment.py
> +class CADeployment(pykube.Deployment):
you can simply call the class `Deployment`, as is hosted in a different module so won't clash with pykube, but if you think that might cause confusion that call it `CustomDeployment` or `AppsV1Deployment`

2020-06-10 13:26 UTC, michelesr commented on cadeployment.py
> +# extends pykube.Deployment, overriding version "v1beta1" with "apps/v1"
the comment here should say overriding version `extensions/v1beta1` with `apps/v1`

2020-06-11 12:38 UTC, zhelyan approved these changes

2020-06-11 13:00 UTC, michelesr approved these changes

2020-06-11 13:01 UTC, merged