Update pykube-ng and restrict RBAC permissions
citizensadvice/kube-schedule-scaler pull request #4
Opened 2021-11-15 10:42 UTC by teqwve

Hi!

First of all, thanks for creating this fork, it's really great how simple it is :)

This PR replaces pykube by pykube-ng (which is its maintained fork) and uses updated version to weaken RBAC permissions required by `kube-schedule-scaler` fixing a potential security issue. It's enough to just grant permissions to patch "deployments/scale" subresource ([apparently available even in 1.18](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18#replace-scale-deployment-v1-apps), I haven't looked on older versions) and thus allow this code only to scale deployments, not change them in an arbitrary way :)

To maintain a compatibility with previous deployments (there is 'master' tag used in example :/) I had to add some workaround, it's in the last commit.

I tested it on running 1.21 kubernetes cluster with different rbac versions. I can also test never versions with minikube. Moreover, I have a draft of e2e tests that starts different minikube versions, runs some deployments and runs kube-schedule-scaler against them. If you'd like I'd be very happy to finish them and submit here.

2021-11-15 23:33 UTC, teqwve commented
Oh, and this PR has a side-effect of fixing docker builds. Apparently some dependency of pykube refuses to be built inside this docker image. With pykube-ng everything works like a charm

2022-03-21 19:03 UTC, michelesr commented on schedule_scaling/main.py
> +    return pykube.HTTPClient(pykube.KubeConfig.from_env())
Does this work both from service account and local kube config?

2022-03-21 19:08 UTC, michelesr commented on schedule_scaling/main.py
> +    return pykube.HTTPClient(pykube.KubeConfig.from_env())
Looks like it: https://codeberg.org/hjacobs/pykube-ng/src/branch/main/pykube/config.py#L103

2022-03-21 19:09 UTC, michelesr commented
@teqwve thanks for this and sorry for reviewing so late... can you please resolve the conflicts so we can merge?

2022-03-21 19:16 UTC, michelesr requested changes
Please resolve conflicts. The rest looks good, thanks!

2022-05-17 16:51 UTC, merged