Handle missed schedules
citizensadvice/kube-schedule-scaler pull request #5
Opened 2021-11-16 00:06 UTC by teqwve

Hi!

This PR adds handling for two types of missed schedules:
* schedules missed due to kube-schedule-scaler being down (like schedules that happen at the same time as a container restart, a container deployment, a cloud preemptible instance release, and so on)
* schedules missed because of main loop executing for longer than 1 minute (rather theoretical, but who knows... maybe with a huge number of deployments it could happen?)

New feature is disabled by default and default behavior should be almost the same as before. I tested it manually on 1.21 cluster, I can test on other versions in minikube (and add e2e tests I've mentioned in other PR as well).

2021-11-16 00:28 UTC, teqwve commented on schedule_scaling/main.py
> +    time = croniter(schedule, now + timedelta(seconds=1)).get_prev()
Now times are rounded up to a minute and we can't rely on any nanoseconds added by `datetime.now()` to make `get_prev()` return current minute...

More specifically: before not-rounded datetime.now() was used here and it was equal to 'BASE_MINUTE + same seconds / some milliseconds', those seconds / milliseconds made `get_prev` return current minute when schedule was happening now (like, current minute is 16:30, schedule is "30 16 * * *", now returns "16:30:00.100). With my changes now is rounded up to a minute so I have to add this margin explicitly

2022-03-21 18:38 UTC, michelesr commented
@teqwve thanks for this, unfortunately due to a problem with notifications I've seen this for the first time right now. I'll have a look tomorrow and provide some feedback

2022-03-21 19:18 UTC, michelesr requested changes
We added timezone support meanwhile, could you please try to integrate your changes with it?

2025-04-13 13:50 UTC, michelesr commented
@teqwve I'm going to close this PR as it's been opened for a while without no progress. I'm also not sure this feature is worthy adding complexity to the code base that is quite minimal, and I'm afraid of unhandled edge cases so I'm not really confident in accepting it.

2025-04-13 13:50 UTC, closed without merging

2025-06-20 19:08 UTC, teqwve commented
Sure. Sorry, I didn't have time to focus on this PR back then